// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("t")
type adjacently = 
  | A
  | B({ c: (int) })
  | C({ c: {  } })
  | D({ c: { y: int, } })
