// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type a = 
  | @as("MESSAGE_ONE") MessageOne({ sender_id: string, number_of_snakes: BigInt.t, })
  | @as("MESSAGE_TWO") MessageTwo({ senderId: string, numberOfCamels: BigInt.t, })
