// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type b = 
  | @as("SnakeMessage") MessageOne({ sender_id: string, number_of_snakes: BigInt.t, })
  | @as("CamelMessage") MessageTwo({ sender_id: string, number_of_camels: BigInt.t, })
