// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("kind")
type c = 
  | @as("SQUARE_THING") SquareThing({ name: string, })
