// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type genericContainer<A, B = int> = {
  a: genericType<(string, string), array<(string, int)>>,
  b: genericType<(A, string), array<(B, int)>>,
  c: genericType<(A, string), array<(genericType<(A, string), array<(B, int)>>, int)>>,
}
