use std::{
    collections::{HashMap, HashSet},
    fs::File,
    io::{Seek, SeekFrom},
    path::{Path, PathBuf},
    sync::{Mutex, OnceLock},
};

pub use error::ExportError;
pub(crate) use recursive_export::export_all_into;

use crate::{Config, TS};

mod error;
mod path;

static EXPORT_PATHS: OnceLock<Mutex<HashMap<PathBuf, HashSet<String>>>> = OnceLock::new();

fn get_export_paths<'a>() -> &'a Mutex<HashMap<PathBuf, HashSet<String>>> {
    EXPORT_PATHS.get_or_init(Default::default)
}

const NOTE: &str = "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n@@warning(\"-30\")\n";

mod recursive_export {
    use std::{any::TypeId, collections::HashSet};

    use super::export_into;
    use crate::{Config, ExportError, TypeVisitor, TS};

    /// Exports `T` to the file specified by the `#[ts(export_to = ..)]` attribute within the given
    /// base directory.  
    /// Additionally, all dependencies of `T` will be exported as well.
    pub(crate) fn export_all_into<T: TS + ?Sized + 'static>(
        cfg: &Config,
    ) -> Result<(), ExportError> {
        let mut seen = HashSet::new();
        export_recursive::<T>(cfg, &mut seen)
    }

    struct Visit<'a> {
        cfg: &'a Config,
        seen: &'a mut HashSet<TypeId>,
        error: Option<ExportError>,
    }

    impl TypeVisitor for Visit<'_> {
        fn visit<T: TS + 'static + ?Sized>(&mut self) {
            // if an error occurred previously, or the type cannot be exported (it's a primitive),
            // we return
            if self.error.is_some() || <T as crate::TS>::output_path().is_none() {
                return;
            }

            self.error = export_recursive::<T>(self.cfg, self.seen).err();
        }
    }

    // exports T, then recursively calls itself with all of its dependencies
    fn export_recursive<T: TS + ?Sized + 'static>(
        cfg: &Config,
        seen: &mut HashSet<TypeId>,
    ) -> Result<(), ExportError> {
        if !seen.insert(TypeId::of::<T>()) {
            return Ok(());
        }

        export_into::<T>(cfg)?;

        let mut visitor = Visit {
            cfg,
            seen,
            error: None,
        };
        <T as crate::TS>::visit_dependencies(&mut visitor);

        if let Some(e) = visitor.error {
            Err(e)
        } else {
            Ok(())
        }
    }
}

/// Export `T` to the file specified by the `#[ts(export_to = ..)]` attribute
pub(crate) fn export_into<T: TS + ?Sized + 'static>(cfg: &Config) -> Result<(), ExportError> {
    let path = <T as crate::TS>::output_path()
        .ok_or_else(std::any::type_name::<T>)
        .map_err(ExportError::CannotBeExported)?;
    let path = cfg.export_dir.join(path);

    export_to::<T, _>(cfg, path::absolute(path)?)
}

/// Export `T` to the file specified by the `path` argument.
pub(crate) fn export_to<T: TS + ?Sized + 'static, P: AsRef<Path>>(
    cfg: &Config,
    path: P,
) -> Result<(), ExportError> {
    let path = path.as_ref().to_owned();
    let type_name = <T as crate::TS>::ident(cfg);

    let buffer = export_to_string::<T>(cfg)?;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    export_and_merge(path, type_name, buffer)?;

    Ok(())
}

/// Exports the type to a new file if the file hasn't yet been written to.
/// Otherwise, finds its place in the already existing file and inserts it.
fn export_and_merge(
    path: PathBuf,
    type_name: String,
    generated_type: String,
) -> Result<(), ExportError> {
    use std::io::{Read, Write};

    let lock = &mut get_export_paths().lock().unwrap();

    let Some(entry) = lock.get_mut(&path) else {
        let mut file = File::create(&path)?;
        file.write_all(generated_type.as_bytes())?;
        file.sync_all()?;

        let mut set = HashSet::new();
        set.insert(type_name);
        lock.insert(path, set);

        return Ok(());
    };

    if entry.contains(&type_name) {
        return Ok(());
    }

    let mut file = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(&path)?;

    let file_len = file.metadata()?.len();

    let mut original_contents = String::with_capacity(file_len as usize);
    file.read_to_string(&mut original_contents)?;

    let original_contents = normalize_declarations(&original_contents);

    let buffer = merge(original_contents, generated_type);

    let buffer = make_mutually_recursive(&buffer);

    file.seek(SeekFrom::Start(0))?;
    file.set_len(0)?;
    file.write_all(NOTE.as_bytes())?;
    file.write_all(b"\n")?;
    file.write_all(buffer.trim_start_matches('\n').as_bytes())?;
    file.sync_all()?;

    entry.insert(type_name);

    Ok(())
}

/// Normalize `type rec` and `and` back to plain `type` so the merge
/// algorithm can work with a uniform format.
fn normalize_declarations(content: &str) -> String {
    content
        .lines()
        .map(|line| {
            if line.starts_with("type rec ") {
                format!("type {}", &line["type rec ".len()..])
            } else if line.starts_with("and ") {
                format!("type {}", &line["and ".len()..])
            } else {
                line.to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// When a file contains multiple type declarations, convert them to
/// `type rec ... and ...` so that types can reference each other
/// regardless of declaration order.
fn make_mutually_recursive(declarations: &str) -> String {
    let type_count = declarations
        .lines()
        .filter(|line| line.starts_with("type "))
        .count();

    if type_count <= 1 {
        return declarations.to_owned();
    }

    let mut result = String::with_capacity(declarations.len() + 4);
    let mut is_first = true;

    for line in declarations.lines() {
        if !result.is_empty() {
            result.push('\n');
        }

        if line.starts_with("type ") {
            if is_first {
                result.push_str("type rec ");
                result.push_str(&line["type ".len()..]);
                is_first = false;
            } else {
                result.push_str("and ");
                result.push_str(&line["type ".len()..]);
            }
        } else {
            result.push_str(line);
        }
    }

    result
}

const HEADER_ERROR_MESSAGE: &str = "The generated strings must have their NOTE separated from their type declarations by a new line";

const DECLARATION_START: &str = "type ";

/// Inserts the declaration from the newly generated type into the contents
/// of the file, organizing declarations alphabetically.
fn merge(original_contents: String, new_contents: String) -> String {
    let (_, original_decls) = original_contents
        .split_once("\n\n")
        .expect(HEADER_ERROR_MESSAGE);
    let (_, new_decl) = new_contents.split_once("\n\n").expect(HEADER_ERROR_MESSAGE);

    let capacity = original_decls.len() + new_decl.len() + 2;

    let mut buffer = String::with_capacity(capacity);

    let new_decl = new_decl.trim_matches('\n');

    let new_decl_name = new_decl
        .split(DECLARATION_START)
        .last()
        .unwrap()
        .split_whitespace()
        .next()
        .unwrap();

    let original_decls: Vec<_> = original_decls
        .split("\n\n")
        .map(|x| x.trim_matches('\n'))
        .collect();

    let mut inserted = false;
    for decl in &original_decls {
        let decl_name = decl
            .split(DECLARATION_START)
            .last()
            .unwrap()
            .split_whitespace()
            .next()
            .unwrap();

        if inserted || decl_name < new_decl_name {
            buffer.push('\n');
            buffer.push_str(decl);
            buffer.push('\n');
        } else {
            buffer.push('\n');
            buffer.push_str(new_decl);
            buffer.push('\n');

            buffer.push('\n');
            buffer.push_str(decl);
            buffer.push('\n');

            inserted = true;
        }
    }

    if !inserted {
        buffer.push('\n');
        buffer.push_str(new_decl);
        buffer.push('\n');
    }

    buffer
}

/// Returns the generated definition for `T`.
pub(crate) fn export_to_string<T: TS + ?Sized + 'static>(
    cfg: &Config,
) -> Result<String, ExportError> {
    let mut buffer = String::with_capacity(1024);
    buffer.push_str(NOTE);
    buffer.push('\n');
    generate_decl::<T>(cfg, &mut buffer);
    buffer.push('\n');
    Ok(buffer)
}

/// Push the declaration of `T`
fn generate_decl<T: TS + ?Sized>(cfg: &Config, out: &mut String) {
    if let Some(docs) = <T as crate::TS>::docs() {
        out.push_str(&docs);
    }

    out.push_str(&<T as crate::TS>::decl(cfg));
}
