// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type myEnum = 
  | Variant0
  | Variant1
  | Variant2
  | Variant3
