// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type myStruct = {
  my_field_0: bool,
  my_field_1: int,
  my_field_2: option<int>,
  my_field_3: option<int>,
  my_field_4: option<int>,
  my_field_5: string,
}
