// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type myType = {
  my_field_0: bool,
  my_field_1: Dict.t<myStruct>,
}
