// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

/**
 * Doc comment.
 * Supports new lines.
 *
 * Testing
 */
type b = {
  
/**
 * Doc of field
 *
 * Testing
 */
name: string,
}
