// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

/**
 * Doc comment.
 * Supports new lines.
 *
 * Testing
 */
@tag("type")
type f = 
  | VarA
  | VarB({ value: array<never> })
  | VarC({ value: { 
/**
 * Doc of field of variant
 *
 * Testing
 */
variant_field: int, } })
