// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type g = { 
/**
 * Docs
 */
some_other_field: int, } & (| VarA | VarB({ value: array<never> }) | VarC({ value: { 
/**
 * Doc of field of variant
 *
 * Testing
 */
variant_field: int, } }))
