// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

/**
 *line 115
 */
type i = {
  
/**
 *column 32
 */
a: int,
  
/**
 *path integration::docs
 */
b: int,
}
