// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type struct = { a: array<string>, b: (array<string>, array<string>), c: (array<string>, array<string>, array<string>), }
