// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type structNested = {
  a: array<array<string>>,
  b: (array<array<string>>, array<array<string>>),
  c: (array<array<string>>, array<array<string>>, array<array<string>>),
}
