// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type structnested = { a: array<array<string>>, b: (array<array<string>>, array<array<string>>), c: (array<array<string>>, array<array<string>>, array<array<string>>), }
