// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type taskStatus2 = 
  | Running({ value: { @as("started-time") started-time_: string, } })
  | Terminated({ value: { status: int, stdout: string, stderr: string, } })
  | A({ value: int })
  | B({ value: (int, int) })
  | C
