// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type taskStatus = 
  | @as("running") Running({ startedTime: string, })
  | @as("terminated") Terminated({ status: int, stdout: string, stderr: string, })
