// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("tag")
type a = 
  | A({ content: a })
  | B({ content: a })
  | C({ content: a })
  | D({ content: a })
  | E({ content: array<a> })
  | F({ content: { a: a, b: a, c: Dict.t<a>, d: option<a>, e?: option<a>, f?: a, } })
  | G({ content: (array<a>, (a, a, a, a), Dict.t<a>) })
