// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type e = 
  | A({ value: e })
  | B({ value: e })
  | C({ value: e })
  | D({ value: e })
  | E({ value: (e, e, e, e) })
  | F({ value: { a: e, b: e, c: Dict.t<e>, d: option<e>, e?: option<e>, f?: e, } })
  | G({ value: (array<e>, array<e>, Dict.t<e>) })
