// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type t = {
  t_box: t,
  self_box: t,
  t_ref: t,
  self_ref: t,
  t_arc: t,
  self_arc: t,
  has_t: { t: t, },
}
