// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type inputfield = | Label({ text: string, }) | Input({ name: option<string>, placeholder: option<string>, default: option<string>, } & (| Text | Expression | Number({ min: option<int>, max: option<int>, }) | Dropdown({ options: array<(string, string)>, })))
