// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type renameSerdeSpecialChar = {
  @as("a/b") a/b_: int,
}
