// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type renameAllScreamingKebab = {
  @as("CRC32C-HASH") CRC32C-HASH_: int,
  @as("SOME-FIELD") SOME-FIELD_: int,
  @as("SOME-OTHER-FIELD") SOME-OTHER-FIELD_: int,
}
