// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type containerWithDefault = { g: genericWithDefault<string>, gi: { t: string, }, t: int, }
