// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type container = {
  foo: generic<int>,
  bar: array<generic<int>>,
  baz: Dict.t<generic<string>>,
}
