// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type cTraitBounds<T, K = int> = 
  | A({ value: { t: T, } })
  | B({ value: T })
  | C
  | D({ value: (T, K) })
