// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type genericParent<T> = {
  a_t: t1<t0<T>>,
  b_t: t1<p1<t0<p0<T>>>>,
  c_t: t1<p1<T>>,
  a_null: t1<t0<unit>>,
  b_null: t1<p1<t0<p0<unit>>>>,
  c_null: t1<p1<unit>>,
}
