// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type genericEnum<A, B, C> = 
  | A({ value: A })
  | B({ value: (B, B, B) })
  | C({ value: array<C> })
  | D({ value: array<array<array<A>>> })
  | E({ value: { a: A, b: B, c: C, } })
  | X({ value: array<int> })
  | Y({ value: int })
  | Z({ value: array<array<int>> })
