// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type parent = {
  a: t1<t0<int>>,
  b: t1<p1<t0<p0<int>>>>,
  c: t1<p1<unit>>,
}
