// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type struct<T> = {
  a: T,
  b: (T, T),
  c: (T, (T, T)),
  d: (T, T, T),
  e: ((T, T), (T, T), (T, T)),
  f: array<T>,
  g: array<array<T>>,
  h: array<((T, T), (T, T), (T, T))>,
}
