// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type rangetest = { a: { start: int, end: int }, b: { start: string, end: string }, c: { start: { start: int, end: int }, end: { start: int, end: int } }, d: { start: int, end: int }, e: { start: Inner, end: Inner }, }
