// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

@tag("type")
type enumwithinternaltag = | A({ foo: string, }) | B({ bar: int, })
