// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

/**
 * Mixed enum: unit variants + payload variants under `@tag`.
 * Unit variants must emit `| Variant({})` so ReScript encodes them as
 * `{"type": "Variant"}` (an object) instead of a plain string, matching
 * what serde's `#[serde(tag = "type")]` expects on the Rust side.
 */
@tag("type")
type mixedTaggedEnum = 
  | UnitA({})
  | UnitB({})
  | WithData({ value: float, })
