// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type simpleEnum = 
  | A({ value: string })
  | B({ value: int })
  | C
  | D({ value: (string, int) })
  | E({ value: foo })
  | F({ value: { a: int, b: string, } })
