// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("kind")
type complexEnum = 
  | A
  | B({ data: { foo: string, bar: float, } })
  | W({ data: simpleEnum })
  | F({ data: { nested: simpleEnum, } })
  | T({ data: (int, simpleEnum) })
