// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type structWithTuples = {
  a: (dep1, dep1),
  b: (dep2, dep2),
  c: (dep4<dep3>, dep4<dep3>),
}
