// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type structwithtuples = { a: (Dep1, Dep1), b: (Dep2, Dep2), c: (Dep4<Dep3>, Dep4<Dep3>), }
