// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type fullOfRefs = {
  str_slice: string,
  ref_slice: array<string>,
  num_ref: int,
}
