// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type fullofrefs = { str_slice: string, ref_slice: array<string>, num_ref: int, }
