#![allow(dead_code)]

use std::{concat, fs};

use rescript_rs::{Config, TS};

#[derive(TS)]
#[rescript(export_to = "export_manually/UserFile.ts")]
struct User {
    name: String,
    age: i32,
    active: bool,
}

#[derive(TS)]
#[rescript(export_to = "export_manually/dir/")]
struct UserDir {
    name: String,
    age: i32,
    active: bool,
}

#[test]
fn export_manually() {
    let cfg = Config::from_env();
    User::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n",
        "\ntype user = { name: string, age: int, active: bool, }",
        "\n",
    );

    let actual_content = super::read_file::<User>(&cfg);
    assert_eq!(actual_content, expected_content);
}

#[test]
fn export_manually_dir() {
    let cfg = Config::from_env();
    UserDir::export(&cfg).unwrap();

    let expected_content = concat!(
        "// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.\n",
        "\ntype userdir = { name: string, age: int, active: bool, }",
        "\n",
    );

    let actual_content = super::read_file::<UserDir>(&cfg);
    assert_eq!(actual_content, expected_content);
}
