// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

@tag("kind")
type complexenum = | A | B({ data: { foo: string, bar: float, } }) | W({ data: SimpleEnum }) | F({ data: { nested: SimpleEnum, } }) | V({ data: array<Series> }) | U({ data: User })
