// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type gender = | @as("MALE") Male | @as("FEMALE") Female | @as("OTHER") Other
