// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type user = { user_id: int, first_name: string, last_name: string, role: Role, family: array<User>, gender: | @as("MALE") Male | @as("FEMALE") Female | @as("OTHER") Other, token: string, created_at: string, }
