// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type vehicle = 
  | @as("bicycle") Bicycle({ color: string, })
  | @as("car") Car({ brand: string, color: string, })
