// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type override = {
  a: int,
  x: { a: int, b: int, c: int, },
  y: externalTypeDef,
  z: (int, externalTypeDef, int),
}
