// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type enum<A, B> = 
  | A({ value: A })
  | B({ value: B })
  | AB({ value: (A, B) })
