// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type named = { a: option<int>, b?: bool, c?: option<int>, d?: option<int>, e: option<int>, f?: int, }
