// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type override = {
  a: int,
  b: 0 | 1 | 2,
  x: string,
  y: string,
  z: string | null,
}
