// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.

type simple = { a: int, b: string, c: (int, string, int), d: array<string>, e: option<string>, f: string, g: option<string>, }
