// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type inline = {
  x: { a?: int, b?: option<int>, c: option<int>, },
}
