// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type nullableStruct = {
  a?: option<int>,
  b?: option<int>,
  c?: option<int>,
  d: int,
  e?: option<int>,
  f?: option<int>,
  g: string,
  h: string,
  i?: int,
  j: option<int>,
}
