// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type optionalInEnum = 
  | A({ a?: int, })
  | B({ b: option<string>, })
