// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

@tag("type")
type optionalFieldsEnumNotNullableVariantOverride = 
  | A({ a?: option<int>, })
  | B({ b: string, c: option<bool>, })
