// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type optionalStruct = {
  a?: int,
  b?: int,
  c?: option<int>,
  d: int,
  e?: int,
  f?: int,
  g: string,
  h: string,
}
