// This file was generated by [rescript-rs](https://github.com/nicholasgasior/rescript-rs). Do not edit this file manually.
@@warning("-30")

type nestedExternally = { u: int, } & (| Baz({ a: int, a2: string, }) | Biz({ b: bool, }) | Buz({ c: string, d: option<int>, }))
